### ISSUE TITLE
ionic cordova build ios ERROR

### ISSUE THREAD

**Issue by bhumin3i** [tripflex/WifiWizard2#20]
wifiwizard2 2.1.0 "WifiWizard2"

```
ld: warning: directory not found for option '-L/Users/bhumin/Library/Developer/Xcode/DerivedData/RTI-aqtvytpqvcxbkaepcfkfyqitbgqv/Build/Products/Debug-iphonesimulator/nanopb'
Undefined symbols for architecture x86_64:
  "_OBJC_CLASS_$_NEHotspotConfigurationManager", referenced from:
      objc-class-ref in WifiWizard2.o
  "_OBJC_CLASS_$_NEHotspotConfiguration", referenced from:
      objc-class-ref in WifiWizard2.o
ld: symbol(s) not found for architecture x86_64
clang: error: linker command failed with exit code 1 (use -v to see invocation)

** BUILD FAILED **
```

also remove command Not working

 ```
cordova plugin remove wifiwizard2 --save
(node:79689) UnhandledPromiseRejectionWarning: Unhandled promise rejection (rejection id: 1): Error: Cannot find module '../node_modules/xml2js'
(node:79689) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.
```

**Comment by saoron** [comment]
Connect your iPhone to your mac and try again, This helped me overcome this issue.

**Comment by bhandaribhumin** [comment]
@saoron thanks for help now I’m outstation, sure I’ll try your tweek but I’m facing this issue after update google map plugin I’m  getting those errors

**Comment by arsenal942** [comment]
As @saoron said and if you read the documentation I provided in https://github.com/arsenal942/Cordova-Network-Manager (and also in the ReadMe for this plugin) it clearly states that the plugin can't run in the simulator. This is due to NEHotspotConfigurationManager (Network Extensions) not being able to run in the simulator. 

You must have a physical iOS enabled device connected to your machine before building.

@tripflex Close this issue.

**Comment by saoron** [comment]
your could also compile cordova with a --device flag

    cordova build ios --device

**Comment by bhandaribhumin** [comment]
@saoron thanks sorry for late reply we must have a physical ios device connected to machine before building app and it works :) i'll close this tomorrow 👍
