### ISSUE TITLE
UWP support?

### ISSUE THREAD

**Issue by ArosPrince** [tripflex/WifiWizard2#24]
### Issue type
Select all that apply
- [ ] Bug
- [ ] Enhancement
- [ ] Task
- [x] Question
- [ ] Other

### Description

Any chance to support Windows UWP? I guess it should be possible...

**Comment by tripflex** [comment]
At this time I do not, as I do not have any use case scenarios myself for anything like this, but i'm completely open to pull requests if you would like to submit one for adding these kind of features.
