### ISSUE TITLE
WifiWizard2.iOSConnectNetwork    wifi free

### ISSUE THREAD

**Issue by Hippoi** [tripflex/WifiWizard2#30]
﻿
Is it possible to connect to a wifi without a password? , when I try it in IOS the app stops working

My code

 WifiWizard2.iOSConnectNetwork(mired, mipass,
        //success
        function () {
          navigator.notification.alert("Connect to SSID = " + mired + " is ok", alertDismissed(), 'title', 'Ok');           
        },
        //fail
        function () {
            navigator.notification.alert(ins_error + mired, alertDismissed(), 'title', 'Ok');
        }

    );

**Comment by arsenal942** [comment]
@Hippoi I will provide this functionality soon in https://github.com/arsenal942/Cordova-Network-Manager. ETA ~3-5days.

@tripflex Once I have performed these changes, I will create a PR for you on this commit.

**Comment by danielavrella** [comment]
@arsenal942 I really need that too. 
Any updates?

**Comment by danielavrella** [comment]
Really need this too. @Hippoi did you get any further?

**Comment by arsenal942** [comment]
@danielavrella Sorry for the delay. Would you prefer it to be a new method 'iOSConnectToFreeWifi' or to be an extra parameter in the existing method? My preference is the latter.

**Comment by tripflex** [comment]
@Hippoi I know it is possible with Android, but i don't know about iOS ... i'm actually working on getting an iOS device as i will need it to test my mobile app for an iot project, but as of right now i don't have one to do any dev work with unfortunately

**Comment by tripflex** [comment]
@Hippoi @danielavrella I added this to be released in 3.1.0 tonight, can you please test this out and let me know if it works for you (i don't have iOS device to test)
