### ISSUE TITLE
Is it possible to connect to a hidden ssid?

### ISSUE THREAD

**Issue by Racroix** [tripflex/WifiWizard2#32]
### Issue type
Select all that apply
- [ ] Bug
- [ ] Enhancement
- [ ] Task
- [x] Question
- [ ] Other

### Description
Can I connect to a hidden ssid via the WifiWizard2.connect() or WifiWizard2.enable() functions?

**Comment by tripflex** [comment]
You should be able to, if not let me know and I'll do some testing on my end

**Comment by Racroix** [comment]
thank you for the reply.

I am testing with Samsung Galaxy S6, S9, NOTE2.

This is my sample connect code.
conn() {
    let ssid = 'BASEIN-DEV1';
    let pwd = '0123456789';
    let wifi = WifiWizard2.formatWPAConfig(ssid, pwd);
    //let wifi = WifiWizard2.formatWifiConfig(ssid, pwd, 'WPA');

    WifiWizard2.add(wifi).then(r => {
//      alert(r);
      WifiWizard2.enable(ssid, true, 10000).then(r1 => {
//        alert(r1);
        WifiWizard2.connect(ssid, false, pwd, 'WPA');
      });
    });
  }

If the SSID is not hidden, the connection will work well.
However, if you hide the SSID, only the network is added and no connection attempt is made.

-1. AP configuration hidden ssid = false.
![image](https://user-images.githubusercontent.com/17863984/39030754-030e4c0c-449f-11e8-8c1c-742a5741f6d5.png)

-2. Advanced - Network Management - Added BASEIN-DEV1 to the list.
![image](https://user-images.githubusercontent.com/17863984/39030903-f1f5e7ee-449f-11e8-9b73-bd5c1c944fcd.png)

-3. connected to BASEIN-DEV1 via my conn () function.
![image](https://user-images.githubusercontent.com/17863984/39030624-159169b4-449e-11e8-9019-3fa6cc3b4083.png)

-4.  AP configuration hidden ssid = true.
![image](https://user-images.githubusercontent.com/17863984/39030931-26681ce0-44a0-11e8-983c-f8e762d3c77b.png)

-5. I removed BASEIN-DEV1 from the list.
![image](https://user-images.githubusercontent.com/17863984/39030997-95ab757a-44a0-11e8-9ed5-53db3b668147.png)

-6. I ran the Conn () function again, but only the network was added and no connection was made.
![image](https://user-images.githubusercontent.com/17863984/39031101-44ff33fe-44a1-11e8-97b8-7adbf36a1a0a.png)

Thank you.

**Comment by Racroix** [comment]
Maybe it's settled.
I refer to the solution of this site.
https://stackoverflow.com/questions/31960984/android-connect-to-known-hidden-wi-fi-network

I made changes to the next 3 files and tested them.
..\node_modules\wifiwizard2\src\android\wifiwizard2\WifiWizard2.java
..\platforms\android\src\android\wifiwizard2\WifiWizard2.java
..\wifiwizard2\src\android\wifiwizard2\WifiWizard2.java

I added it to the 
'private boolean add(CallbackContext callbackContext, JSONArray data) method'.
/*
wifi.hiddenSSID = true; // add.
*/

and I added it to the
 'private boolean connect(CallbackContext callbackContext, JSONArray data) method'.
/*
wifiManager.disconnect(); // add.
wifiManager.enableNetwork(networkIdToConnect, true); //Existing code.
wifiManager.reconnect(); // add.
*/

It works!
