### ISSUE TITLE
IOS app breaks when WIFI password is shorter than 8 characters

### ISSUE THREAD

**Issue by AndreFWeber** [tripflex/WifiWizard2#34]
﻿

### Prerequisites

Check all boxes if you have done the following:
- [x] Checked that your issue isn't already filed: https://github.com/tripflex/wifiwizard2/issues
- [x] Make sure you fill out the Issue Type below

### Issue type
Select all that apply
- [x] Bug
- [x] Enhancement
- [ ] Task
- [ ] Question
- [ ] Other

### Description
First of all: Great plugin! Very handy and useful!

The IOS call to connect() breaks the IOS app whenever the user inserts a WIFI password shorter than 8 characters. 

It's well know that the WPA/WPA2 password length should be at least 8 character long and the app developer can easily prohibit the user for attempting such a connection. 

But it would be nice to have a fail callback so the app won't break in case the developer forgets to verify the password length.

### Steps to Reproduce
On an IOS device try to connect on an WIFI network with a password shorter than 8 characters.

**Expected behavior:** [What you expect to happen]
Connect to a WIFI network.

**Actual behavior:** [What actually happens]
2018-04-23 17:18:31.209909-0300 EasyKey[3954:1944346] [] -[NEHotspotConfiguration valid:726  NEHotspotConfiguration invalid WPA/WPA2 passphrase length.
(lldb) 

**Reproduces how often:** [What percentage of the time does it reproduce?]

Everytime.

### Versions

Test were made on IONIC built app running on an iPhone (IOS 11).

**Comment by arsenal942** [comment]
I designed it like this on purpose. The developer **should** know and verify the password when it is being entered. WPA/WPA2 won't accept passwords of a length shorter than 8.

That being said, I will expand the plugin to allow the user to specify if they are using WPA to connect. Right now it is a hard-coded boolean.

**Comment by tripflex** [comment]
@arsenal942 we could possibly just add a few lines of code to reject the promise if the password is less than 8 chars, thoughts?

**Comment by tripflex** [comment]
@arsenal942 yes I completely agree, but there may be situations where the dev has no control over the network type ... possibly ... but yes, WEP is super easy to hack 😛

**Comment by tripflex** [comment]
@AndreFWeber fixed in 113ad4747aea18c70e6b652084f87195fd6496e8
