### ISSUE TITLE
Broken compatibility with older versions of Android

### ISSUE THREAD

**Issue by training91** [tripflex/WifiWizard2#35]
### Prerequisites

Check all boxes if you have done the following:
- [X] Checked that your issue isn't already filed: https://github.com/tripflex/wifiwizard2/issues
- [X] Make sure you fill out the Issue Type below

### Issue type
Select all that apply
- [x] Bug
- [ ] Enhancement
- [ ] Task
- [ ] Question
- [ ] Other

### Description

The instruction at line **56** of the file WifiWizard2/www/**WifiWizard2.js** (let networkInformation = [];) is not supported by older webviews with older versions of javascript and is currently breaking the compatibily of the plugin with older versions of Android.
Possible fixes:
- change it to **var networkInformation = [];**

### Steps to Reproduce

1. Start the app
2. An error in javascript blocks the application

**Expected behavior:** Plugin should work on Android SDK versions <= 21 (Android Kitkat and older).

**Actual behavior:** I receive an error related to the interpretation of Javascript at runtime that prevents the application from working correctly.

**Reproduces how often:** 100% of the times.

### Versions

Plugin version: 3.0.0
OS version: Android Kitkat 4.4.2
Phone: Samsung Galaxy S4 Mini

**Comment by tripflex** [comment]
Thank you for reporting this, it has been fixed in 8c950b1bd452c2033467c25c1e3a47db630494d2
