### ISSUE TITLE
Request for merging other discontinued libraries into WifiWizard2

### ISSUE THREAD

**Issue by DRSDavidSoft** [tripflex/WifiWizard2#4]
### Issue type
- [ ] Bug
- [x] Enhancement
- [ ] Task
- [x] Question
- [ ] Other

### Description
Great project! Thanks for taking over the original WifiWizard, and keeping it under active development.

Would you be interested to also integrate [**cordova-hotspot-plugin**](https://github.com/hypery2k/cordova-hotspot-plugin/blob/develop/PLUGIN_USAGE.MD#cordovapluginshotspot--object)'s features (such as creating a hotspot) into **WifiWizard2**?

I'm developing an app which should be able to a) scan Wifi networks, b) connect to specified SSIDs & c) switch between Wifi and hotspot mode.

Since that project is no longer maintained and the author has abandoned it, I was wondering if you could merge its codebase into *WifiWizard2*, so I can switch to your codebase.

Another feature that I'd really like to see in **WifiWizard2** is an ability to get the current IP address of the device, as seen here: [cordova-plugin-networkinterface](https://github.com/salbahra/cordova-plugin-networkinterface) `networkinterface.getWiFiIPAddress()`.

Of course, as a developer myself I understand if you have limited time, or no interest in adding hotspot support at all. But it would be much appreciate if you could put it into your TODO plans, at least.

This is just for the sake of having a unified codebase for the library. The Java/www source are already out there. Just needs integration and a bit of testing.

I do hope you consider these proposals :)
Thanks for your time

**Comment by bhumin3i** [comment]
not getting connected wifi : (android) 
my code is 
======
```
ionViewDidLoad() {
    console.log("ionViewDidLoad AdvanceMeetingBookingPage");
    this.platform.ready().then(() => {
      this.startScan();
      console.log('networks',this.networks);
  });
  
    this.getFacilityList();
  }
  startScan() {
    if (typeof WifiWizard2 !== 'undefined') {
            console.log("WifiWizard loaded: ");
            console.log(WifiWizard2);
    } else {
        console.warn('WifiWizard not loaded.');
    }              

    let successNetwork = (e: any) => {
      console.log('e',e);
      WifiWizard2.getConnectedSSID(listHandler, failNetwork);
    }

    let failNetwork = (e: any) => {
        console.log("fail : " + e);
    }

    let listHandler = (a: any) => {
        this.networks = [];
        console.log('a',a);
        for (let x in a) {
          console.log('ssid',a[x].SSID);                    
            console.log(a[x].SSID + ", " + a[x].BSSID + ", " + a[x].level);  
            this.networks.push({
                ssid: a[x].SSID,
                bssid: a[x].BSSID,
                level: a[x].level});                
        } 
        console.log('listHandler networks',this.networks);
    }
    WifiWizard2.startScan(successNetwork, failNetwork);
}
```

result in console : 
WifiWizard loaded: 
Object {getCurrentSSID: function, getCurrentBSSID: function, iOSConnectNetwork: function, iOSDisconnectNetwork: function, formatWifiConfig: function…}
networks []
e OK
a []
listHandler networks []

**Comment by tripflex** [comment]
Hey!  This actually isn't a bad idea at all, and to be honest, with the issues that i've just found between older versions of Android (earlier than 8) and Android 8+ (Oreo) i'm going to have to basically rewrite the entire plugin to support both versions.

I'm going to create another issue after this reply to specify everything, so while i'm working on the new code base I will def look at integrating any of these features that I can
