### ISSUE TITLE
some phone show error：Module wifiwizard2.WifiWizard2 does not exist.

### ISSUE THREAD

**Issue by coloz** [tripflex/WifiWizard2#41]
### Prerequisites

Check all boxes if you have done the following:
- [x] Checked that your issue isn't already filed: https://github.com/tripflex/wifiwizard2/issues
- [x] Make sure you fill out the Issue Type below

### Issue type
Select all that apply
- [x] Bug
- [ ] Enhancement
- [ ] Task
- [ ] Question
- [ ] Other

### Description

i have 5 phones，only one show error：
[INFO:CONSOLE(57)] "Uncaught SyntaxError: Block-scoped declarations (let, const, function, class) not yet supported outside strict mode", source: file:///android_asset/www/plugins/wifiwizard2/www/WifiWizard2.js (57)
I/chromium: [INFO:CONSOLE(1461)] "Uncaught Error: Module wifiwizard2.WifiWizard2 does not exist.", source: file:///android_asset/www/cordova.js (1461)

### Versions
android 5.1
ionic 3

**Comment by surajrao** [comment]
I am seeing this in android version 4.4.4 (Samsung Galaxy tablet).

**Comment by jack828** [comment]
Looks like it's due to this line: https://github.com/tripflex/WifiWizard2/blob/master/www/WifiWizard2.js#L56

I've forked this project and I'm currently resolving as many issues as I can - I'll let you both know once this is fixed in my fork.

(of course, I'll be submitting pull requests for everything I fix)

**Comment by kalicki** [comment]
Hey @jack828,
Check this project: https://github.com/arsenal942/Cordova-Network-Manager
@arsenal942 accepts fast pull reqeuest

**Comment by jack828** [comment]
Thanks @kalicki, I'll check it out.

**Comment by tripflex** [comment]
Dohhh!!! Yeah sucks going to ES6/ES7 and having to come back to using `var` instead of `let` ... just an oversight on my part, my bad
