### ISSUE TITLE
Wifi is enabled after call isWifiEnable

### ISSUE THREAD

**Issue by seanyang1984** [tripflex/WifiWizard2#54]
### Issue type
Select all that apply
- [x] Bug
- [ ] Enhancement
- [ ] Task
- [ ] Question
- [ ] Other

### Description
I call isWifiEnabled to check whether wifi is enable, but after call it the wifi will be enabled.

  public boolean execute(String action, JSONArray data, CallbackContext callbackContext)
      throws JSONException {

    boolean wifiIsEnabled = verifyWifiEnabled();

The function verifyWifiEnabled enable wifi.

I think this may be not suitable, because I just want check wifi status, but not change it

### Steps to Reproduce
call isWifiEnabled when wifi is disable

**Expected behavior:** [What you expect to happen]

**Actual behavior:** [What actually happens]

**Reproduces how often:** [What percentage of the time does it reproduce?]

### Versions

Please include the plugin version that you are using and also include the OS, version and device you are using.

### Additional Information

Any additional information, configuration or data that might be necessary to reproduce the issue.

**Comment by seanyang1984** [comment]
boolean wifiIsEnabled = verifyWifiEnabled();     // move to here, is right?
    if (!wifiIsEnabled) {
      callbackContext.error("WIFI_NOT_ENABLED");
      return true; // Even though enable wifi failed, we still return true and handle error in callback
    }

**Comment by tripflex** [comment]
@seanyang1984 yup you are correct!  This should be moved below the android methods that do not require wifi to be enabled, will work on updating it soon

**Comment by devi255** [comment]
> ```
> boolean wifiIsEnabled = verifyWifiEnabled();     // move to here, is right?
> if (!wifiIsEnabled) {
>   callbackContext.error("WIFI_NOT_ENABLED");
>   return true; // Even though enable wifi failed, we still return true and handle error in callback
> }
> ```

thx... is work
WifiWizard2.java line 148 move to line 198
