### ISSUE TITLE
wifiwizard2 2.1.0 getting error 

### ISSUE THREAD

**Issue by bhumin3i** [tripflex/WifiWizard2#57]
PLUGIN version : 
wifiwizard2 2.1.0 "WifiWizard2"

iOS version : **ios12**
 
.ts code

```
 if (typeof WifiWizard2 !== 'undefined') {
      console.log("WifiWizard loaded: ");
      this.selectBuildingOption = false;
      this.isNotconnectwithWifi = false;
      WifiWizard2.getCurrentBSSID(this.successNetwork, this.failNetwork); //always go to failNetwork
    } 
```

Error log in xcode 

```
2018-10-08 16:57:59.043091+0530 @RTI[3797:356306] WifiWizard loaded:
2018-10-08 16:57:59.046592+0530 @RTI[3797:356306] Supported interfaces: (
    en0
)
2018-10-08 16:57:59.046830+0530 @RTI[3797:356306] en0 => (null)
2018-10-08 16:57:59.061072+0530 @RTI[3797:356306] fail : Not available
```

**Comment by sarpherviz** [comment]
I get the "Not Available" error as you on IOS 12

Access Wifi Information : 
To use this function in iOS 12 and later, enable the Access WiFi Information capability for your app in Xcode. When you enable this capability, Xcode automatically adds the Access WiFi Information entitlement to your entitlements file and App ID.

I tried WifiWizard2 latest version and give "Access Wifi Information" on Capabilities screen for local test. getCurrentSSID and getCurrentBSSID functions are running perfectly.

**Comment by bhumin3i** [comment]
I already enabled this capability for APP ID. but I am facing different issue while archive application then this plugin is not working.

**Comment by sarpherviz** [comment]
Sorry for late response, what kind of issue while archiving the application?

**Comment by sarpherviz** [comment]
Please check your plugin.xml file and add wifi-info lines like https://github.com/tripflex/WifiWizard2/blob/master/plugin.xml

**Comment by bhumin3i** [comment]
@sarpherviz tanks. 

my plugin.xml looks like
```

<?xml version="1.0" encoding="UTF-8"?>

<plugin xmlns="http://apache.org/cordova/ns/plugins/1.0"
    xmlns:android="http://schemas.android.com/apk/res/android"
    id="wifiwizard2"
    version="2.1.0">
  
    <name>WifiWizard2</name>
    <description>Cordova Wifi Manager for Android and iOS</description>
    <license>Apache 2.0</license>
    <keywords>cordova,network,wifi,phonegap</keywords>
    <repo>https://github.com/tripflex/wifiwizard2.git</repo>
    <issue>https://github.com/tripflex/wifiwizard2/issues</issue>

    <js-module src="www/WifiWizard2.js" name="WifiWizard2">
      <clobbers target="window.WifiWizard2" />
    </js-module>

    <!-- ES6 promise polyfill -->
    <dependency id="es6-promise-plugin" version="4.1.0" />

  <!-- android -->
    <platform name="android">
      
      <config-file target="AndroidManifest.xml" parent="/manifest">
        <uses-permission android:name="android.permission.ACCESS_WIFI_STATE" />
        <uses-permission android:name="android.permission.ACCESS_NETWORK_STATE" />
        <uses-permission android:name="android.permission.CHANGE_WIFI_STATE" />
        <uses-permission android:name="android.permission.CHANGE_NETWORK_STATE" />
        <uses-permission android:name="android.permission.INTERNET" />
        <uses-permission android:name="android.permission.ACCESS_FINE_LOCATION" />
      </config-file>
      
      <config-file target="res/xml/config.xml" parent="/*">
        <feature name="WifiWizard2">
          <param name="android-package" value="wifiwizard2.WifiWizard2" />
          <param name="onload" value="true" />
        </feature>
      </config-file>

      <source-file src="src/android/wifiwizard2/WifiWizard2.java" target-dir="src/android/wifiwizard2" />
    </platform>

    <platform name="ios">
        <config-file target="config.xml" parent="/*">
            <feature name="WifiWizard2">
                <param name="ios-package" value="WifiWizard2"/>
            </feature>
        </config-file>

        <header-file src="src/ios/WifiWizard2.h" />
        <source-file src="src/ios/WifiWizard2.m" />
        <framework src="SystemConfiguration.framework" />
    </platform>
  
</plugin>

```

let me check with add wifi-info line in plugin.xml

**Comment by sarpherviz** [comment]
I think you have to add HotspotConfiguration , networkextension and wifi-info lines. Hope it will fix your problem.

**Comment by sarpherviz** [comment]
When i install app over Xcode, app was working but if i archived the app and install, WifiWizard2 was not working and return null as you get.

let me explain what i did
 - add lines to plugin.xml
 - remove platform ios
 - add platform ios
 - build over Visual Studio Code terminal with 
          ionic cordova build ios -- --buildFlag="-UseModernBuildSystem=0"
 - open xcode and check the Capabilities, (Access Wifi Information, HotSpot and Network Extension)
 - build and Archive
 - publish .ipa over Microsoft AppCenter
 - Install the app to phone over AppCenter, it is working now.

**Comment by bhumin3i** [comment]
@sarpherviz wow your are awesome bro. it's worked. :)

**Comment by tripflex** [comment]
Seems to be related to this too:
https://github.com/apache/cordova-ios/issues/407
