### ISSUE TITLE
iOS scan "Not supported"

### ISSUE THREAD

**Issue by kaichancoder** [tripflex/WifiWizard2#6]
`WifiWizard2.scan([], function(success) { console.log('success', success); }, function(error) { console.log('error', error); });`

I'm getting: error – "Not supported"

Do I need permission as in:
https://developer.apple.com/library/content/qa/qa1942/_index.html
"NEHotspotHelper requires that your app have special entitlements."

**Comment by tripflex** [comment]
TBH i'm not sure I haven't had a chance to test out the iOS stuff, but IIRC I only think connect and disconnect work for iOS, i will be testing here in the next week or so and will be able to comment for sure on this

**Comment by kaichancoder** [comment]
Ok great thanks, be good to know if you get any further.

**Comment by larryluu** [comment]
I think I have the same mistake.

Do not get to wifi scan on iOS.

My Problem is that startScan give status okay but getScanResult give an empty alert,

**Comment by captainreptile** [comment]
I'm considering implementing this, but biggest concern is IOS Scan, connect/Disconnect capabilities.
Are this working?

**Comment by kaichancoder** [comment]
iOS Scan isn't available on iOS, I confirmed that directly from apple, connect works.

**Comment by tripflex** [comment]
Sorry guys I haven't had a chance to do any testing on iOS devices as the only one I have available is my girl's phone .. and of course she's not going to let me have it for the entire day 😛 

Does anybody have an iPhone they would be willing to do some testing on?

**Comment by captainreptile** [comment]
@tripflex 
The scan doesnt work, at least not in this module - the easiest way for IOS case is to link to the native wifi scanner from the APP..

Apple does seem to offer an option to do wifi scan from the app, but the requirements are pretty high (check for how to apply for MFi program) 

Connect / disconnect does work on IOS.

**Comment by tripflex** [comment]
@captainreptile thank you for the response and letting me know, i'll see if i can find any more information or some other people to maybe help us out on this ... if any of you know any iOS devs, please feel free to invite them to help us out 👍

**Comment by brassier** [comment]
I also got errors when scanning on iOS.  I tried to use `iOSConnectNetwork()` and it seemed to return without actually connecting.  No error or anything.  Has anyone else seen that?

**Comment by arsenal942** [comment]
@brassier That's because I never wrapped it in a `completionHandler`. It is something I am working on in https://github.com/arsenal942/Cordova-Network-Manager which once complete, I will issue a PR so @tripflex can have it in here.

**Comment by brassier** [comment]
@arsenal942 - sorry for the frustration.  The docs have `scan()` as a global function which I assume indicates it is supposed to work on Android and iOS.  If `scan()` will never work for iOS, it may be good to put it under the Android Functions section.

Looking forward to the `completionHandler` update for iOS connecting.

**Comment by tripflex** [comment]
@brassier @arsenal942 that's my fault when adding everything to the readme, since I do not use iOS it must have just been oversight, i'll update the readme

**Comment by luisAzcuaga** [comment]
Any update on this feature?

**Comment by bizr** [comment]
@luisAzcuaga 10 years iOS, WiFi scan API was never available, it's a security feature of iOS, it will never change. The only way to achieve this is by Jailbreak.
