### ISSUE TITLE
can't use with template in Visual Studio

### ISSUE THREAD

**Issue by warriorfenixSM** [tripflex/WifiWizard2#66]
Hi, i try to use your plugin in visual studio with a photroller template ([https://themeforest.net/item/photroller-mobile-tablet-responsive-template/6150430](url)) and i install the plugin throw xml and i see in the dependencies, but i can't use, when i try to use, visual studio return me a error: (TS) Can't find WifiWizard2 name. Could you give some help?.

Thanks for all

**Comment by tripflex** [comment]
@warriorfenixSM there are no types for the javascript as typescript is not used and there are no type defs either ...

Please provide more details about the issue you're having ... are you just referring to intellisense?  I'm sure this has something to do with intellisense and cordova, but with limited information it's hard to even know.  

Are you trying to run this on a device or is this just IDE specific?
