### ISSUE TITLE
WifiWizard2.getConnectedSSID() NOT working with Android >= 8.1

### ISSUE THREAD

**Issue by blondie63** [tripflex/WifiWizard2#67]
### Prerequisites

Check all boxes if you have done the following:
- [X] Checked that your issue isn't already filed: https://github.com/tripflex/wifiwizard2/issues
- [ ] Make sure you fill out the Issue Type below

### Issue type
Select all that apply
- [X] Bug
- [ ] Enhancement
- [ ] Task
- [ ] Question
- [ ] Other

### Description
I tried with permissions also but always return "unknown ssid"
Someone has a solution ?

ps. for iOS no problems

### Versions
3.1.0

**Comment by tripflex** [comment]
Duplicate issue, please continue discussion in #63
