### ISSUE TITLE
Can't fetch plugin

### ISSUE THREAD

**Issue by Sumbersss** [tripflex/WifiWizard2#68]
﻿

### Prerequisites

Check all boxes if you have done the following:
- [X] Checked that your issue isn't already filed: https://github.com/tripflex/wifiwizard2/issues
- [X] Make sure you fill out the Issue Type below

### Issue type
Select all that apply
- [X] Bug
- [ ] Enhancement
- [ ] Task
- [ ] Question
- [ ] Other

### Description

Can't fetch plugin from cordova anymore

### Steps to Reproduce

1. with the command line `cordova plugin add cordova-plugin-wifiwizard2`

**Expected behavior:** should download the plugin

**Actual behavior:**  `ionic cordova plugin add cordova-plugin-wifiwizard2
> cordova plugin add cordova-plugin-wifiwizard2 --save
Failed to fetch plugin git+https://github.com/tripflex/wifiwizard2.git via registry.
Probably this is either a connection problem, or plugin spec is incorrect.
Check your connection and plugin name/version/URL.
Failed to get absolute path to installed module
[ERROR] An error occurred while running subprocess cordova.
        
        cordova plugin add cordova-plugin-wifiwizard2 --save exited with exit code 1.
        
        Re-running this command with the --verbose flag may provide more information.
`

**Reproduces how often:** 100%

### Versions

3.1.0

### Additional Information

**Comment by 13546777510** [comment]
Has this problem been solved? If not solved, try using this cmd code

```
cordova plugin add https://github.com/tripflex/WifiWizard2.git
```

Very happy to help anyone, good luck!

**Comment by mogupta** [comment]
Its not working for me. I am using cordova android 8.0.0 

`ionic cordova plugin add cordova-plugin-wifiwizard2` gives me
```
ionic cordova plugin add cordova-plugin-wifiwizard2 > cordova plugin add cordova-plugin-wifiwizard2 --save (node:13860) UnhandledPromiseRejectionWarning: CordovaError: Failed to fetch plugin git+https://github.com/tripflex/WifiWizard2.git via registry. Probably this is either a connection problem, or plugin spec is incorrect. Check your connection and plugin name/version/URL. Failed to get absolute path to installed module
```
