### ISSUE TITLE
Update npm with latest version 3.1.1

### ISSUE THREAD

**Issue by arsenal942** [tripflex/WifiWizard2#73]
Says it all in the title my friend.

We are now on v3.1.1 so let's update accordingly.

**Comment by tripflex** [comment]
Working on doing this but need to test to make sure as another user reported app crashing after this update

**Comment by kalicki** [comment]
I'm testing in the last 10min and I didn't get any trouble

**Comment by tripflex** [comment]
@kalicki did you use the latest master branch as of 45 minutes ago?  I just pushed an update that recalls getWifiServiceInfo instead of returning an error -- that may be what caused the other user's error on device

**Comment by kalicki** [comment]
@tripflex 
I'm using branch dev.

I did an update a few hours ago I noticed something...
When I enter a page and request the getCurrentSSID it loads first, but when I return and enter again it does not load and gets stuck `verifyWifiEnabled entered`
```
To native (Cordova plugin): callbackId: WifiWizard21118677065, service: WifiWizard2, action: getConnectedSSID, actionArgs: []
WifiWizard2: verifyWifiEnabled entered.
```

**Comment by tripflex** [comment]
done 👍
